Description of multi_fig_save
Home > ephys > helpers > visualization > multi_fig_save.m
multi_fig_save
PURPOSE
SYNOPSIS
function multi_fig_save(fighandle,save_dir,filename,formats,varargin)
DESCRIPTION
 multi_save(fighandle,save_dir,filename,formats)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
greg_proc_data
yoonseob_iccns_figure
ephys_cluster ephys_cluster.m takes extracted and aligned singing data generated by intan_songdet.m
ephys_su_lfp_coherence_ifr ephys_su_lfp_coherence_ifr.m computes rate-triggered LFPs, the script must be run in the directory 'ephys'
ephys_su_lfp_coherence_spect ephys_su_lfp_coherence_tf computes coherency spectra between LFPs and point processes using the
ephys_su_lfp_coherence_tf ephys_su_lfp_coherence_tf computes coherograms between LFPs and point processes using the
ephys_visual_lfp_amp ephys_lfp_amp.m takes data generated by ephys_cluster.m and stored in extracted_data.mat
ephys_visual_lfp_spect this function is incomplete, use at your own risk
ephys_visual_lfp_tf ephys_lfp_tf.m takes data generated by ephys_cluster.m and stored in extracted_data.mat
ephys_visual_mua intan_visual_mua.m takes data generated by intan_cluster.m and stored in extracted_data.mat
ephys_visual_mua_bin intan_visual_mua.m takes data generated by intan_cluster.m and stored in extracted_data.mat
ephys_visual_sua ephys_visual_sua.m takes data generated by intan_cluster.m and stored in extracted_data.mat
ephys_su_lfp_coherence_quickplots
SOURCE CODE
function multi_fig_save(fighandle,save_dir,filename,formats,varargin)
%
% multi_save(fighandle,save_dir,filename,formats)
%
%
%
%
%
renderer='painters';
nparams=length(varargin);
if mod(nparams,2)>0
    error('Parameters must be specified as parameter/value pairs');
end
for i=1:2:nparams
    switch lower(varargin{i})
        case 'renderer'
            renderer=varargin{i+1};
    end
end
renderer=[ '-' renderer];
if nargin<4
    formats='eps,fig,png';
end
try
    if ~isempty(findstr('eps',formats)) || strcmp(formats,'all')
        print(fighandle,'-depsc2',renderer,fullfile(save_dir,[filename '.eps']));
    end
    if ~isempty(findstr('tiffn',formats)) || strcmp(formats,'all')
        print(fighandle,'-dtiffn',renderer,fullfile(save_dir,[filename '.tif']));
        if exist('rsetwrite')>0
            disp('Writing rset...')
            rsetwrite(fullfile(save_dir,[filename '.tif']),fullfile(save_dir,[filename '.rset']));
            response=[];
            while isempty(response)
                response=input('(K)eep the original .tiff or (d)elete?  ','s');
                switch lower(response(1))
                    case 'k'
                        break;
                    case 'd'
                        delete(fullfile(save_dir,[filename '.tif']));
                    otherwise
                        response=[];
                end
            end
        end
    end
    %print(fighandle,'-dtiffn','-r300',fullfile(save_dir,[filename '.tif']));
    if ~isempty(findstr('png',formats)) || strcmp(formats,'all')
        print(fighandle,'-dpng',renderer,'-r200',fullfile(save_dir,[filename '.png']));
    end
    if ~isempty(findstr('fig',formats)) || strcmp(formats,'all')
        saveas(fighandle,fullfile(save_dir,[filename '.fig']));
    end
catch
    disp('Save did not work (running in terminal emulation?)...')
    disp('Trying simple file formats...')
    if ~isempty(findstr('eps',formats)) || strcmp(formats,'all')
        print(fighandle,'-depsc2',renderer,'-r100',fullfile(save_dir,[filename '.eps']));
    end
    if ~isempty(findstr('png',formats)) || strcmp(formats,'all')
        print(fighandle,'-dpng',renderer,'-r100',fullfile(save_dir,[filename '.png']));
    end
    if ~isempty(findstr('fig',formats)) || strcmp(formats,'all')
        saveas(fighandle,fullfile(save_dir,[filename '.fig']));
    end
end
end