Description of ephys_denoise_signal
Home > ephys > helpers > ephys > ephys_denoise_signal.m
ephys_denoise_signal
PURPOSE
takes ephys data from Intan recordings and re-references
SYNOPSIS
function [DATA,CAR]=ephys_denoise_signal(EPHYS_DATA,CHIN,CHOUT,varargin)
DESCRIPTION
takes ephys data from Intan recordings and re-references
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ephys_pipeline_quicklook generates a figure to glance at data extracted by the pipeline
ephys_su_lfp_coherence_ifr computes IFR triggered LFPs
ephys_su_lfp_coherence_spect computes coherency spectra between fields and single units
ephys_su_lfp_coherence_tf computes coherograms between LFPs and single units
ephys_visual_lfp_amp generates song-aligned LFP amplitude rasters
ephys_visual_lfp_tf generates a song-aligned average spectrogram of the LFP
ephys_visual_mua generates song-aligned mult-unit rasters
ephys_visual_sua generates song-aligned single-unit rasters
ephys_su_lfp_coherence_quickplots generates plots with aligned fields, spikes and IFR
ephys_pipeline_candidate_su ephys_candidate_su.m approximates the SNR of channels by
SOURCE CODE
function [DATA,CAR]=ephys_denoise_signal(EPHYS_DATA,CHIN,CHOUT,varargin)
%takes ephys data from Intan recordings and re-references
%
%
%
%
% how to denoise the raw signal, CAR or nearest neighbor
% CHOUT is the channel mapping for the output, CHIN for the input
% i.e. if EPHYS_DATA contains channels 1,2,4,5,6 then CHIN is 1:6
% and if you only want to return channels 1 and 2 set CHOUT to 1:2
if nargin<3 | isempty(CHOUT), CHOUT=CHIN; end
nparams=length(varargin);
if mod(nparams,2)>0
    error('Parameters must be specified as parameter/value pairs');
end
%%%
car_exclude=[];
method='none';
for i=1:2:nparams
    switch lower(varargin{i})
        case 'car_exclude'
            car_exclude=varargin{i+1};
        case 'method'
            method=varargin{i+1};
        otherwise
    end
end
CAR=[];
% intan nearest neighbor mapping
channel_map=[4 3 2 1 16 15 14 13 5 6 7 8 9 10 11 12];
channel_ref=[3 4 3 2 1 16 15 14 6 5 6 7 8 9 10 11];
exclude_channels=[];
for i=1:length(car_exclude)
    exclude_channels(i)=find(CHANNELS==car_exclude(i));
end
car_electrodes=setdiff(1:length(CHIN),exclude_channels); % which electrodes are good for CAR?
ndims_ephys=ndims(EPHYS_DATA);
if ndims_ephys==3
    [samples,ntrials,nchannels]=size(EPHYS_DATA);
elseif ndims_ephys==2
    [samples,nchannels]=size(EPHYS_DATA);
else
    error('Number of dimensions for EPHYS_DATA must be 2 or 3!');
end
% map each channel appropriately
chmap=[];
for i=1:length(CHOUT)
    idx=find(CHOUT(i)==CHIN);
    if ~isempty(idx)
        chmap=[chmap idx];
    end
end
if ndims_ephys==3
    DATA=zeros(samples,ntrials,length(chmap));
    switch lower(method)
        case 'car'
            CAR=mean(EPHYS_DATA(:,:,car_electrodes),3);
            for i=1:length(chmap)
                DATA(:,:,i)=EPHYS_DATA(:,:,chmap(i))-CAR;
            end
        case 'nn'
            for i=1:length(chmap)
                DATA(:,:,i)=EPHYS_DATA(:,:,chmap(i))-EPHYS_DATA(:,:,find(channel_map==chmap(i)));
            end
        otherwise
            for i=1:length(chmap)
                DATA(:,:,i)=EPHYS_DATA(:,:,chmap(i));
            end
    end
else
    DATA=zeros(samples,length(chmap));
    switch lower(method)
        case 'car'
            CAR=mean(EPHYS_DATA(:,car_electrodes),2);
            for i=1:length(chmap)
                DATA(:,i)=EPHYS_DATA(:,chmap(i))-CAR;
            end
        case 'nn'
            for i=1:length(chmap)
                DATA(:,i)=EPHYS_DATA(:,chmap(i))-EPHYS_DATA(:,find(channel_map==chmap(i)));
            end
        otherwise
            for i=1:length(chmap)
                DATA(:,i)=EPHYS_DATA(:,chmap(i));
            end
    end
end